name: Build and Push PotionCraft Images

on:
  pull_request:
    types: [labeled]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: api
            dockerfile: api/Dockerfile
            context: ./api
          - service: frontend
            dockerfile: frontend/Dockerfile
            context: ./frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/potioncraft-${{ matrix.service }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/potioncraft-${{ matrix.service }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/potioncraft-${{ matrix.service }}:pr-${{ github.event.pull_request.number }}